# **Task-1**

Create a data cleaning and preprocessing pipeline for a dataset.

Use a CSV dataset containing missing values, duplicates, and
inconsistent data.

Clean the data by handling missing values, removing duplicates, and
correcting data formats.

Prepare the dataset so it is ready for analysis or modeling.

This task will help you understand the most important step in data
science—cleaning raw data and making it usable for analysis.

In [1]:
# adding lib
import pandas as pd
import numpy as np

In [2]:
# loading dataset
df = pd.read_csv("/content/student-lifestyle-and-stress-dataset.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [3]:
# view dataset
df.head()

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
0,school,6.868702,1.711722,3.176942,NaN,8.0,7.0,2.0,1
1,school,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1
3,school,8.591223,2.384922,5.222832,81.868960,2.0,7.0,7.0,0
4,college,5.329293,9.345179,7.815869,85.847982,5.0,6.0,10.0,1

In [4]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25500 entries, 0 to 25499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_Type        24248 non-null  object
 1   Sleep_Hours         24167 non-null  float64
 2   Study_Hours         24223 non-null  float64
 3   Social_Media_Hours  24188 non-null  float64
 4   Attendance          24195 non-null  float64
 5   Exam_Pressure       24230 non-null  float64
 6   Family_Support      24209 non-null  float64
 7   Month               24186 non-null  float64
 8   Stress_Level        25500 non-null  int64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.8+ MB

In [5]:
# dataset shape
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 25500
Columns: 9

In [6]:
# checking missing values
df.isnull().sum()

Student_Type          1252
Sleep_Hours           1333
Study_Hours           1277
Social_Media_Hours    1312
Attendance            1305
Exam_Pressure         1270
Family_Support        1291
Month                 1314
Stress_Level             0
dtype: int64

In [7]:
# checking duplicate records
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 24

In [8]:
# removing duplicate
df = df.drop_duplicates()

print("Shape After Removing Duplicates:")
print(df.shape)

Shape After Removing Duplicates:
(25476, 9)

In [9]:
# identifying numerical columns
num_cols = df.select_dtypes(include=['int64','float64']).columns

print(num_cols)

Index(['Sleep_Hours', 'Study_Hours', 'Social_Media_Hours', 'Attendance',
       'Exam_Pressure', 'Family_Support', 'Month', 'Stress_Level'],
      dtype='object')

In [10]:
# filling missing values
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

print("Numerical Missing Values Handled")

Numerical Missing Values Handled

In [11]:
# Identifyinc catogerical columns
cat_cols = df.select_dtypes(include=['object']).columns

print(cat_cols)

Index(['Student_Type'], dtype='object')

In [12]:
# filling missing catagorical values
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Categorical Missing Values Handled")

Categorical Missing Values Handled

In [13]:
# verifying missing values
df.isnull().sum()

Student_Type          0
Sleep_Hours           0
Study_Hours           0
Social_Media_Hours    0
Attendance            0
Exam_Pressure         0
Family_Support        0
Month                 0
Stress_Level          0
dtype: int64

In [14]:
#standardize text columns
for col in cat_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

print("Text Formatting Completed")

Text Formatting Completed

In [15]:
# checking data type
df.dtypes

Student_Type           object
Sleep_Hours           float64
Study_Hours           float64
Social_Media_Hours    float64
Attendance            float64
Exam_Pressure         float64
Family_Support        float64
Month                 float64
Stress_Level            int64
dtype: object

In [16]:
# Statistical Summary
df.describe()

,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
count,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000
mean,6.463091,4.688690,3.552719,81.302928,5.351311,5.807976,6.475389,0.299851
std,1.464487,2.184630,1.852293,11.740114,2.334919,2.175324,3.366705,0.458201
min,2.008586,-1.433434,0.000040,-5.000000,1.000000,1.000000,1.000000,0.000000
25%,5.510233,3.157381,2.234549,74.280603,4.000000,4.000000,4.000000,0.000000
50%,6.542207,4.538138,3.501057,81.941554,5.000000,6.000000,6.000000,0.000000
75%,7.473658,6.035742,4.774688,89.580536,7.000000,7.000000,9.000000,1.000000
max,9.997527,22.444460,9.962134,120.000000,10.000000,10.000000,12.000000,1.000000

In [17]:
# detect and handel outlaires
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

print("Outliers Handled")

Outliers Handled

In [18]:
# encoding catagorical variables
df_clean = pd.get_dummies(df, drop_first=True)

print("New Shape:", df_clean.shape)

New Shape: (25476, 10)

In [19]:
# feature scqaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [20]:
# save cleaned dataset
df_clean.to_csv(
    "cleaned_student_lifestyle_stress_dataset.csv",
    index=False
)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [21]:
# final dataset
df_clean.head()

,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level,Student_Type_school,Student_Type_working_student
0,6.868702,1.711722,3.176942,81.941554,8.0,7.0,2.0,1.0,True,False
1,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1.0,True,False
2,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1.0,False,False
3,8.591223,2.384922,5.222832,81.868960,2.0,7.0,7.0,0.0,True,False
4,5.329293,9.345179,7.815869,85.847982,5.0,6.0,10.0,1.0,False,False

In [22]:
# final verification
print("Final Shape:", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated().sum())

Final Shape: (25476, 10)

Missing Values:
0

Duplicate Rows:
3

In [23]:
# Show duplicate rows

duplicates = df[df.duplicated()]
duplicates

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
9288,college,4.715047,10.353283,5.482923,74.256757,8.0,6.0,10.0,1.0
25248,college,6.651795,10.353283,0.876000,71.510549,4.0,6.0,12.0,0.0
25303,college,4.072348,10.353283,6.025272,72.317118,4.0,5.0,2.0,1.0

In [24]:
# Remove duplicates

df = df.drop_duplicates()

print("Duplicate rows after removal:", df.duplicated().sum())

Duplicate rows after removal: 0

In [25]:
# Show duplicate rows

duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [Student_Type, Sleep_Hours, Study_Hours, Social_Media_Hours, Attendance, Exam_Pressure, Family_Support, Month, Stress_Level]
Index: []